buffer: Implement `set_hidden` and `set_unhidden`
poljar/rust-weechat pull request #31
Opened 2021-02-04 11:50 UTC by yayayayaka

This PR introduces two setter functions `set_hidden()` and
`set_unhidden()` in the `Buffer` module to hide or unhide a buffer from the
buflist.

2021-02-04 16:30 UTC, poljar requested changes
I think `hide()` and `unhide()` are better names for those methods, the CI error is unrelated to this and only on nightly.

2021-02-04 17:09 UTC, poljar commented
The CI issue should be gone if you rebase this PR onto current master.

2021-02-05 18:30 UTC, yayayayaka commented
> I think `hide()` and `unhide()` are better names for those methods

Alright, just updated the code.

2021-02-05 19:38 UTC, merged

2021-02-05 19:38 UTC, poljar commented
Thanks.